export interface Establishment {
  id: string;
  name: string;
  category: string;
  rating: number;
  deliveryTime: string;
  deliveryFee: number;
  minOrderValue: number;
  isOpen: boolean;
  open?: boolean;
  active: boolean;
  acceptingOrders?: boolean;
  temporarilyPaused?: boolean;
  pausedUntil?: string | null;
  suspended?: boolean;
  featured: boolean;
  image: string;
  logoUrl?: string | null;
  coverImageUrl?: string | null;
  phone: string;
  email: string;
  owner: string;
  address: string;
  city: string;
  cityId: string;
  cityName: string;
  state: string;
  document: string;
  companyName: string;
  platformFeePercent: number;
  bairro?: string;
  cep?: string;
  atendeRetirada?: boolean;
  entregaPropria?: boolean;
  acceptsDelivery?: boolean;
  acceptsPickup?: boolean;
  aboutDescription?: string;
  acceptedPaymentMethods?: string[];
  bairrosAtendidos?: string;
  acceptCash?: boolean;
  acceptPix?: boolean;
  acceptDebitCard?: boolean;
  acceptCreditCard?: boolean;
  acceptContactless?: boolean;
  acceptDeliveryPayment?: boolean;
  acceptPickupPayment?: boolean;
  description?: string;
  baseEstimatedMinutes?: number;
  platformStatus?: 'active' | 'inactive' | 'archived';
  categoryName?: string;
  operationalPause?: boolean;
  legalContactName?: string;
  legalContactPhone?: string;
  legalContactEmail?: string;
  ownerUid?: string;
  merchantUid?: string;
  deliverySettings?: {
    enabled: boolean;
    defaultDeliveryFee: number;
    defaultMinimumOrderValue: number;
    defaultAdditionalMinutes: number;
    cityId: string;
    cityName: string;
    coverageMode?: 'entire_city' | 'listed_zones_only';
  };
}
